name: text-style-mimicry
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch
  # - pytorch::torchvision #not needed for .txt ft
  # - pytorch::torchaudio #same
  - pytorch-cuda=11.8
  - huggingface_hub
  - transformers
  - datasets
  - peft
  - accelerate
  - wandb
  - pytest
  - boto3
  - pyyaml
  - bzip2
  - pip
  - pip:
    - unsloth

