name: text-style-mimicry-updated
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # Core
  - python=3.12
  - bzip2
  - pip

  # Hugging Face
  - transformers=4.55.*
  - datasets>=3,<4
  - peft=0.17.*
  - accelerate=1.10.*
  - huggingface_hub=0.34.*

  # Tooling
  - wandb>=0.21,<0.22
  - pytest>=8.4
  - boto3>=1.34
  - pyyaml>=6.0

  # Pip extras
  - pip:
      - --extra-index-url=https://download.pytorch.org/whl/cu128
      - torch==2.7.0
      - bitsandbytes==0.46.1     # keep explicit
      - unsloth>=2025.7,<2025.9