name: text-style-mimicry
channels:
  - pytorch
  - nvidia
  - conda-forge
  - unsloth
dependencies:
  - python=3.10
  - pytorch::pytorch
  # - pytorch::torchvision #not needed for .txt ft
  # - pytorch::torchaudio #same
  - pytorch-cuda=11.8
  - unsloth::unsloth
  - huggingface_hub
  - transformers
  - datasets
  - peft
  - accelerate
  - wandb
  - pytest
  - boto3
  - pyyaml
